spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  web:
    resources:
      static-locations: file:qr-output/

naver:
  api:
    base-url: https://openapi.naver.com/v1/search/book.json
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}

openai:
  api:
    key: ${OPENAI_API_KEY}